### PR TITLE
Update samples with latest changes in OS repo

### PR DESCRIPTION
**Pull request by austinkinross**

### CODE REVIEW

**Comment by sebmerry** [comment]
@austinkinross  Can you please revert the change to the VRS md file? That looks like a change that needs to go to the OS repo.

**Review by sebmerry — CHANGES_REQUESTED** [review]
Please revert the VR md changes, that needs to go to the OS repo.

**Comment by austinkinross** [comment]
> Please revert the VR md changes, that needs to go to the OS repo.

Sure, good catch

**Comment by austinkinross** [comment]
Thanks Seb!

**Pull request merged**
