### PR TITLE
fix crash on shutdown where the engine attempted to use debugInterfac…

### PR DESCRIPTION
**Pull request by missmah**
…e even if it was null. Added an assert for now - but should likely change this to spawn a message to the user if we care (or, just skip the debug checks silently, if we don't)...

### CODE REVIEW

**Comment by bobbrow** [comment]
Thanks for reporting this.  We tend to test the code on systems with the debug layers installed.

It is better practice to check the return code from QueryInterface since I have seen bugs in the past where the output pointer is not properly initialized by an API in the failure case.  If you update it to "if (SUCCEEDED(g_Device->QueryInterface(&debugInterface)))" I can merge this in.

Thanks again.

**Comment by bobbrow** [comment]
Hi- I didn't hear back from you, so we will go ahead and make this change directly in the branch and close this pull request.

**Comment by missmah** [comment]
‎I was just doing it now - but either way is fine :)

Sent from my BlackBerry 10 smartphone.
From: Bob Brown
Sent: Wednesday, September 2, 2015 17:57
To: Microsoft/DirectX-Graphics-Samples
Reply To: Microsoft/DirectX-Graphics-Samples
Cc: Mah, Layla
Subject: Re: [DirectX-Graphics-Samples] fix crash on shutdown where the engine attempted to use debugInterfac… (#17)



Hi- I didn't hear back from you, so we will go ahead and make this change directly in the branch and close this pull request.

**Comment by bobbrow** [comment]
Ok.  If you're working on it, please continue.  I was going to wait a day for a reply and then make the change.  I should have written that originally.

**Comment by missmah** [comment]
I think GitHub added the new commit to this pull request -- but please let me know if it didn't make it :)

**Comment by bobbrow** [comment]
Merged it. Thanks!

**Pull request merged**
