### PR TITLE
Makes NVidia Card Default in Ambient Occlusion example.

### PR DESCRIPTION
**Pull request by BrennerLittle**
I'm not sure if this is the proper way to make this fix, but it worked for me. There may be unintended consequences though but I cant imagine what they would be.

### CODE REVIEW

**Comment by walbourn** [comment]
The proper fix is to modify:

```
https://github.com/microsoft/DirectX-Graphics-Samples/blob/master/Samples/Desktop/D3D12Raytracing/src/D3D12RaytracingRealTimeDenoisedAmbientOcclusion/SampleCore/util/DeviceResources.cpp
```

In the ``InitializeAdapter`` method, instead of using the standard ``EnumAdapter`` method, use:

```
    ComPtr<IDXGIAdapter1> adapter;
    ComPtr<IDXGIFactory6> factory6;
    HRESULT hr = m_dxgiFactory.As(&factory6);
    if (FAILED(hr))
    {
        throw exception("DXGI 1.6 not supported");
    }
    for (UINT adapterID = 0; DXGI_ERROR_NOT_FOUND != factory6->EnumAdapterByGpuPreference(adapterID, DXGI_GPU_PREFERENCE_HIGH_PERFORMANCE, IID_PPV_ARGS(&adapter)); ++adapterID)
    {
```

The other Raytracing samples are already doing this.
```

**Review by walbourn — CHANGES_REQUESTED** [review]
See the comments on the proper way to fix this issue with the different DXGI method.

**Comment by BrennerLittle** [comment]
I believe I added the proper code to fix the issue.

**Comment by BrennerLittle** [comment]
Do I need to close this pull request and add a newer cleaner pull request with only one commit?

**Pull request merged**
